import { StyleSheet } from "react-native";

import { palette } from "@/src/theme/palette";

export const styles = StyleSheet.create({
  content: {
    paddingBottom: 52,
  },
  hero: {
    overflow: "hidden",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: palette.heroBackground,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    gap: 10,
  },
  heroOrbPrimary: {
    position: "absolute",
    top: -90,
    right: -20,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: palette.heroOrbPrimary,
  },
  heroOrbSecondary: {
    position: "absolute",
    bottom: -80,
    left: -50,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: palette.heroOrbSecondary,
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  addressBlock: {
    flex: 1,
    gap: 2,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 18,
    backgroundColor: "rgba(255,250,244,0.82)",
  },
  addressLabel: {
    fontSize: 8,
    lineHeight: 13,
    fontWeight: "700",
    color: palette.heroAccentText,
  },
  addressRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  addressValue: {
    flex: 1,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "700",
    color: palette.foreground,
  },
  addressSubtext: {
    paddingLeft: 22,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  actions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  cartBubble: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: palette.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  cartCounter: {
    position: "absolute",
    top: 2,
    right: 2,
    minWidth: 18,
    height: 18,
    borderRadius: 999,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.foreground,
  },
  cartCounterText: {
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "800",
    color: palette.surface,
  },
  profileBubble: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FFF2D9",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#F3D797",
  },
  profileBubbleSignedIn: {
    backgroundColor: "#EAF2FF",
    borderColor: "#CFE0FF",
  },
  profileBubbleText: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "800",
    color: palette.sky,
  },
  profileImage: {
    width: "100%",
    height: "100%",
  },
  searchCategoryPanel: {
    gap: 10,
    borderRadius: 24,
    padding: 10,
    backgroundColor: "rgba(255,255,255,0.82)",
    borderWidth: 1,
    borderColor: "rgba(255,224,236,0.92)",
    shadowColor: "rgba(31,36,48,0.10)",
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    minHeight: 50,
    paddingHorizontal: 12,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#F2E0EA",
  },
  searchIconBubble: {
    width: 32,
    height: 32,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF0F6",
  },
  searchInput: {
    flex: 1,
    minHeight: 20,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "800",
    color: palette.mutedForeground,
    paddingVertical: 0,
    textAlignVertical: "center",
  },
  homeCategoryBlock: {
    gap: 8,
  },
  homeCategoryHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  homeCategoryTitle: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "800",
    color: palette.foreground,
  },
  homeCategorySubtitle: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  homeCategorySeeAll: {
    minHeight: 30,
    borderRadius: 12,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#FFF0F6",
  },
  homeCategorySeeAllText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    color: palette.secondary,
  },
  homeCategoryRow: {
    gap: 8,
    paddingRight: 4,
  },
  homeCategoryChip: {
    minWidth: 86,
    minHeight: 42,
    borderRadius: 14,
    paddingHorizontal: 9,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderWidth: 1,
    borderColor: "rgba(31, 36, 48, 0.06)",
  },
  homeCategoryIconWrap: {
    width: 26,
    height: 26,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.76)",
  },
  homeCategoryChipText: {
    flex: 1,
    minWidth: 0,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    color: palette.foreground,
  },
  clearButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1D9",
  },
  bannerCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 24,
  },
  bannerCopy: {
    flex: 1,
    gap: 6,
  },
  bannerChip: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
  },
  bannerChipText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
  },
  bannerTitle: {
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "800",
  },
  bannerSubtitle: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
  },
  bannerButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 13,
    paddingVertical: 11,
    borderRadius: 999,
  },
  bannerButtonText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: "#fff",
  },
  campaignCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 22,
    overflow: "hidden",
  },
  campaignImage: {
    width: 84,
    height: 84,
    borderRadius: 18,
    backgroundColor: "#FFFFFF80",
  },
  campaignCarousel: {
    maxWidth: 118,
  },
  campaignCarouselImage: {
    width: 76,
    height: 76,
    marginRight: 8,
    borderRadius: 16,
    backgroundColor: "#FFFFFF80",
  },
  campaignCopy: {
    flex: 1,
    gap: 6,
  },
  campaignBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
  },
  campaignBadgeText: {
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "800",
  },
  campaignTitle: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "900",
  },
  campaignSubtitle: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    opacity: 0.78,
  },
  campaignAction: {
    paddingHorizontal: 11,
    paddingVertical: 9,
    borderRadius: 999,
  },
  campaignActionText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "900",
    color: "#fff",
  },
  campaignModalOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 50,
    justifyContent: "center",
    padding: 22,
  },
  campaignModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(35, 24, 30, 0.45)",
  },
  campaignModalCard: {
    borderRadius: 26,
    backgroundColor: palette.surface,
    padding: 18,
    gap: 12,
  },
  homeModalCard: {
    width: "100%",
    minHeight: 420,
    maxHeight: "84%",
    borderRadius: 18,
    backgroundColor: palette.surface,
    padding: 14,
    gap: 12,
    overflow: "hidden",
  },
  campaignModalClose: {
    position: "absolute",
    top: 12,
    right: 12,
    zIndex: 2,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.82)",
  },
  campaignModalImage: {
    width: "100%",
    height: 160,
    borderRadius: 20,
    backgroundColor: "#FFF1F6",
  },
  homeModalImage: {
    width: "100%",
    minHeight: 260,
    flex: 1,
    borderRadius: 10,
    backgroundColor: "#FFF1F6",
  },
  homeModalImageOnly: {
    minHeight: 340,
  },
  campaignModalTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "900",
    color: palette.foreground,
  },
  campaignModalSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  campaignModalAction: {
    alignItems: "center",
    borderRadius: 999,
    backgroundColor: palette.primary,
    paddingVertical: 13,
  },
  campaignModalActionText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
    color: "#fff",
  },
  nearbySpinnerShell: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  nearbySpinnerRing: {
    position: "absolute",
    width: 25,
    height: 25,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: "rgba(255,92,147,0.18)",
    borderTopColor: palette.secondary,
    borderRightColor: palette.secondary,
  },
  nearbySpinnerCore: {
    width: 19,
    height: 19,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF0F6",
  },
  offerChipRow: {
    paddingRight: 10,
    gap: 8,
  },
  offerChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "#FFF1F6",
  },
  offerChipText: {
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "800",
    color: "#B23B70",
  },
  cmsBlock: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 22,
    overflow: "hidden",
  },
  cmsBlockImageOnlyShell: {
    padding: 0,
    gap: 0,
  },
  cmsBlockImage: {
    width: 82,
    height: 82,
    borderRadius: 18,
    backgroundColor: "#FFFFFF80",
  },
  cmsImageOnly: {
    width: "100%",
    height: 112,
    borderRadius: 0,
    backgroundColor: "#FFFFFF80",
  },
  cmsCarouselOnly: {
    position: "relative",
  },
  cmsCarouselOnlySlide: {
    width: 330,
    marginRight: 10,
    borderRadius: 14,
    overflow: "hidden",
  },
  cmsCarouselOnlyImage: {
    width: "100%",
    height: 112,
    borderRadius: 14,
    backgroundColor: "#FFF1F6",
  },
  cmsBlockCarousel: {
    width: 92,
  },
  cmsCarouselWrap: {
    width: 92,
    gap: 7,
  },
  cmsCarouselImage: {
    width: 92,
    height: 74,
    borderRadius: 16,
    backgroundColor: "#FFFFFF80",
  },
  cmsCarouselDots: {
    position: "absolute",
    bottom: 9,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "center",
    gap: 4,
  },
  cmsCarouselDot: {
    width: 5,
    height: 5,
    borderRadius: 999,
    backgroundColor: "rgba(63,36,50,0.22)",
  },
  cmsCarouselDotActive: {
    width: 14,
    backgroundColor: "#FF5C93",
  },
  cmsBlockCopy: {
    flex: 1,
    gap: 6,
  },
  cmsBlockBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
  },
  cmsBlockBadgeText: {
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "900",
  },
  cmsBlockTitle: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "900",
  },
  cmsBlockSubtitle: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    opacity: 0.78,
  },
  cmsInlineButton: {
    alignSelf: "flex-start",
    marginTop: 2,
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
  },
  cmsInlineButtonSoft: {
    backgroundColor: "rgba(255,255,255,0.62)",
  },
  cmsInlineButtonOutline: {
    backgroundColor: "transparent",
  },
  cmsInlineButtonDark: {
    backgroundColor: "#2B1D24",
    borderColor: "#2B1D24",
  },
  cmsInlineButtonText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "900",
    color: "#fff",
  },
  genZLoaderCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.78)",
    borderWidth: 1,
    borderColor: "#FFE0EC",
  },
  genZLoaderIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF0F6",
  },
  genZLoaderCopy: {
    flex: 1,
    gap: 2,
  },
  genZLoaderTitle: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "900",
    color: palette.foreground,
  },
  genZLoaderSubtitle: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
    color: palette.mutedForeground,
  },
  shimmerBlock: {
    position: "relative",
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.64)",
  },
  shimmerHighlight: {
    position: "absolute",
    top: -16,
    bottom: -16,
    width: 82,
    backgroundColor: "rgba(255,255,255,0.72)",
  },
  homeHeroSkeleton: {
    gap: 10,
  },
  homeBannerSkeleton: {
    height: 112,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.56)",
    borderWidth: 1,
    borderColor: "rgba(255,224,236,0.9)",
  },
  skeletonChipRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  skeletonChipWide: {
    width: 130,
    height: 31,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.58)",
  },
  skeletonChip: {
    width: 96,
    height: 31,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.52)",
  },
  skeletonChipSmall: {
    width: 72,
    height: 31,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.48)",
  },
  restaurantSkeletonCard: {
    overflow: "hidden",
    borderRadius: 28,
    backgroundColor: palette.surface,
    shadowColor: palette.shadow,
    shadowOpacity: 0.82,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  restaurantSkeletonImage: {
    height: 148,
    backgroundColor: "#FFF0F6",
  },
  restaurantSkeletonCopy: {
    padding: 14,
    gap: 13,
  },
  restaurantSkeletonTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 14,
  },
  restaurantSkeletonTitleBlock: {
    flex: 1,
    gap: 8,
  },
  restaurantSkeletonTitle: {
    width: "72%",
    height: 18,
    borderRadius: 999,
    backgroundColor: "#FFF1E8",
  },
  restaurantSkeletonSubtitle: {
    width: "52%",
    height: 12,
    borderRadius: 999,
    backgroundColor: "#F7EEF3",
  },
  restaurantSkeletonPrice: {
    width: 66,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FFF1F6",
  },
  restaurantSkeletonMetricRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  restaurantSkeletonMetric: {
    width: 76,
    height: 24,
    borderRadius: 999,
    backgroundColor: "#FFF7EF",
  },
  restaurantSkeletonMetricSmall: {
    width: 62,
    height: 24,
    borderRadius: 999,
    backgroundColor: "#FFF7EF",
  },
  guideSection: {
    paddingTop: 18,
    gap: 10,
  },
  guideCard: {
    marginHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 22,
  },
  guideIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.7)",
  },
  guideCopy: {
    flex: 1,
    gap: 3,
  },
  guideTitle: {
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "900",
  },
  guideSubtitle: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    opacity: 0.72,
  },
  guideButton: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
  },
  guideButtonText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "900",
    color: "#fff",
  },
  guideImageRow: {
    paddingLeft: 20,
    paddingRight: 10,
    gap: 10,
  },
  guideImageCard: {
    width: 116,
    gap: 6,
  },
  guideImage: {
    width: 116,
    height: 86,
    borderRadius: 16,
    backgroundColor: "#EDF4FF",
  },
  guideImageTitle: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "800",
    color: palette.foreground,
  },
  section: {
    paddingTop: 22,
    gap: 14,
  },
  sectionHeaderWrap: {
    paddingHorizontal: 20,
  },
  nearbySectionHeaderRow: {
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
  },
  nearbySectionHeaderCopy: {
    flex: 1,
  },
  horizontalRow: {
    paddingLeft: 20,
    paddingRight: 10,
    gap: 14,
  },
  featuredCardWrap: {
    width: 286,
  },
  verticalList: {
    paddingHorizontal: 20,
    gap: 16,
  },
  feedbackCard: {
    marginHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderRadius: 22,
    backgroundColor: palette.surface,
  },
  feedbackText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  browseAllButton: {
    marginHorizontal: 20,
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 15,
    borderRadius: 20,
    backgroundColor: palette.surface,
  },
  browseAllButtonText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "800",
    color: palette.foreground,
  },
});
