import { StyleSheet } from "react-native";

import { palette } from "@/src/theme/palette";

export const styles = StyleSheet.create({
  content: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  headerWrap: {
    paddingTop: 12,
    paddingBottom: 16,
  },
  headerCard: {
    borderRadius: 30,
    backgroundColor: palette.surface,
    padding: 14,
    gap: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  filterButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: palette.secondary,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    flexShrink: 0,
    shadowColor: palette.shadow,
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  filterBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.foreground,
  },
  filterBadgeText: {
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "800",
    color: palette.surface,
  },
  searchBar: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 44,
    paddingHorizontal: 13,
    borderRadius: 18,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: "#ECEEF5",
    shadowColor: palette.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
    color: palette.foreground,
    paddingVertical: 0,
  },
  clearButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F6F0F4",
  },
  filterChip: {
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "#F7F2F6",
    borderWidth: 1,
    borderColor: "#F0E5EC",
  },
  filterChipActive: {
    backgroundColor: palette.secondary,
    borderColor: palette.secondary,
  },
  filterChipText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.foreground,
  },
  filterChipTextActive: {
    color: palette.surface,
  },
  sortRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  sortSummary: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.mutedForeground,
  },
  clearFiltersBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "#F5EFF4",
  },
  clearFiltersBadgeText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "800",
    color: palette.foreground,
  },
  historyBlock: {
    gap: 10,
  },
  historyLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: palette.foreground,
  },
  recentSearchRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  recentSearchChip: {
    flexDirection: "row",
    alignItems: "center",
    maxWidth: "100%",
    borderRadius: 999,
    backgroundColor: "#F6F2F8",
  },
  recentSearchMain: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingLeft: 12,
    paddingRight: 6,
    paddingVertical: 9,
  },
  recentSearchText: {
    maxWidth: 150,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.foreground,
  },
  recentSearchRemove: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 4,
  },
  recentVisitedRow: {
    paddingRight: 8,
    gap: 12,
  },
  recentVisitedCardWrap: {
    width: 232,
  },
  recentVisitedCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 22,
    backgroundColor: palette.surface,
    padding: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  recentVisitedThumb: {
    width: 64,
    height: 64,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#F7F1F7",
  },
  recentVisitedImage: {
    width: "100%",
    height: "100%",
  },
  recentVisitedImageFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F7F1F7",
  },
  recentVisitedCopy: {
    flex: 1,
    gap: 3,
  },
  recentVisitedTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  recentVisitedSubtitle: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  recentVisitedMeta: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    color: "#AA6A87",
  },
  recentVisitedHeart: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F6F1F5",
  },
  recentVisitedHeartActive: {
    backgroundColor: palette.secondary,
  },
  feedbackCard: {
    minHeight: 56,
    paddingHorizontal: 16,
    borderRadius: 24,
    backgroundColor: palette.surface,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  feedbackText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
    color: palette.foreground,
  },
  filterModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(20, 24, 35, 0.32)",
    justifyContent: "center",
    padding: 18,
  },
  filterModalCard: {
    borderRadius: 30,
    backgroundColor: palette.surface,
    padding: 22,
    gap: 18,
    shadowColor: palette.shadow,
    shadowOpacity: 0.18,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 14 },
    elevation: 12,
    borderWidth: 1,
    borderColor: "#E8EDF5",
    overflow: "hidden",
    position: "relative",
  },
  filterAccentOrb: {
    position: "absolute",
    width: 132,
    height: 132,
    borderRadius: 66,
    backgroundColor: "#FCE2EC",
    top: -34,
    right: -26,
  },
  filterModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    zIndex: 1,
  },
  filterPill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#FFF1F6",
    marginBottom: 12,
  },
  filterPillText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "800",
    color: "#D85A8A",
  },
  filterModalTitle: {
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
    color: palette.foreground,
  },
  filterModalSubtitle: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500",
    color: palette.mutedForeground,
    maxWidth: 220,
  },
  filterModalClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F3F5FA",
    alignItems: "center",
    justifyContent: "center",
  },
  filterSection: {
    gap: 12,
    padding: 15,
    borderRadius: 24,
    backgroundColor: "#FFFBFD",
    borderWidth: 1,
    borderColor: "#F4E7EE",
    shadowColor: palette.shadow,
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  filterSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  filterSectionIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1F6",
  },
  filterSectionLabel: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  filterOptionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  filterFooter: {
    flexDirection: "row",
    gap: 10,
  },
  filterResetButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 18,
    backgroundColor: "#FFF5EF",
    alignItems: "center",
    justifyContent: "center",
  },
  filterResetText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  filterApplyButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 20,
    backgroundColor: "#FF5A92",
    alignItems: "center",
    justifyContent: "center",
  },
  filterApplyText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.surface,
  },
});
