import { StyleSheet } from "react-native";

import { palette } from "@/src/theme/palette";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: palette.background },
  content: { gap: 16, paddingBottom: 32 },
  topHeader: {
    paddingHorizontal: 18,
    paddingTop: 8,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
    shadowColor: palette.shadow,
    shadowOpacity: 0.8,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  headerCopy: { flex: 1, gap: 2 },
  kicker: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    letterSpacing: 1,
    textTransform: "uppercase",
    color: palette.primary,
  },
  title: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "800",
    color: palette.foreground,
  },
  subtitle: {
    fontSize: 12,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  heroCard: {
    marginHorizontal: 18,
    padding: 16,
    borderRadius: 28,
    backgroundColor: palette.surface,
    gap: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 0.9,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  heroCardTint: {
    backgroundColor: "#FFF7FB",
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  heroLogoWrap: {
    width: 56,
    height: 56,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: palette.surfaceMuted,
  },
  heroLogo: {
    width: "100%",
    height: "100%",
  },
  heroLogoFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
  },
  heroCopy: { flex: 1, gap: 6 },
  statusPill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
  },
  statusPillText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
  },
  heroMeta: {
    fontSize: 13,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  heroSummaryRow: {
    flexDirection: "row",
    gap: 10,
  },
  heroMetric: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: palette.surfaceMuted,
    gap: 2,
  },
  heroMetricValue: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  heroMetricLabel: {
    fontSize: 12,
    lineHeight: 16,
    color: palette.mutedForeground,
    fontWeight: "600",
  },
  successFlashCard: {
    marginHorizontal: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 24,
    backgroundColor: palette.successSurface,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.45,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  successFlashIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFFCC",
  },
  successFlashCopy: {
    flex: 1,
    gap: 2,
  },
  successFlashTitle: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
    color: palette.foreground,
  },
  successFlashSubtitle: {
    fontSize: 12,
    lineHeight: 17,
    color: palette.mutedForeground,
  },
  liveCard: {
    marginHorizontal: 18,
    gap: 10,
  },
  reorderActionButton: {
    minHeight: 74,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: palette.secondary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.8,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  reorderActionButtonDisabled: {
    opacity: 0.8,
  },
  reorderActionIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  reorderActionCopy: {
    flex: 1,
    gap: 4,
  },
  reorderActionTitle: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
    color: "#fff",
  },
  reorderActionSubtitle: {
    fontSize: 12,
    lineHeight: 17,
    color: "rgba(255,255,255,0.82)",
  },
  cancelledStateCard: {
    minHeight: 110,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 0.7,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  cancelledStateIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelledStateCopy: { flex: 1, gap: 4 },
  cancelledStateTitle: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
    color: palette.foreground,
  },
  cancelledStateSubtitle: {
    fontSize: 13,
    lineHeight: 19,
    color: palette.mutedForeground,
  },
  trackLiveButton: {
    minHeight: 66,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: palette.foreground,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.8,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  trackLiveIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  trackLiveButtonCopy: { flex: 1, gap: 4 },
  trackLiveButtonTitle: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
    color: "#fff",
  },
  trackLiveButtonSubtitle: {
    fontSize: 12,
    lineHeight: 17,
    color: "rgba(255,255,255,0.74)",
  },
  actionButtonColumn: { gap: 10 },
  secondaryActionButton: {
    minHeight: 46,
    borderRadius: 999,
    backgroundColor: palette.surface,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: palette.shadow,
    shadowOpacity: 0.7,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  secondaryActionButtonDanger: {
    backgroundColor: "#FFF0F6",
    borderWidth: 1,
    borderColor: "#FFD6C9",
  },
  secondaryActionButtonText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  secondaryActionButtonTextDanger: {
    color: palette.primary,
  },
  sectionCard: {
    marginHorizontal: 18,
    padding: 16,
    borderRadius: 28,
    backgroundColor: palette.surface,
    gap: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 0.75,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  sectionCardRose: {
    backgroundColor: "#FFF8FB",
  },
  sectionCardSky: {
    backgroundColor: "#F7FAFF",
  },
  sectionCardSand: {
    backgroundColor: "#FFFBF6",
  },
  sectionCardMint: {
    backgroundColor: "#F7FFFB",
  },
  sectionCardLavender: {
    backgroundColor: "#FAF8FF",
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  sectionTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "800",
    color: palette.foreground,
  },
  sectionHint: {
    fontSize: 12,
    lineHeight: 16,
    color: palette.mutedForeground,
  },
  miniTimelineScroll: {
    paddingHorizontal: 4,
    paddingBottom: 12,
    gap: 8,
  },
  miniTimelineItem: {
    minWidth: 96,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  miniTimelineDot: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceMuted,
  },
  miniTimelineDotDone: {
    backgroundColor: palette.mint,
    borderColor: palette.mint,
  },
  miniTimelineLabel: {
    minWidth: 48,
    fontSize: 12,
    lineHeight: 16,
    color: palette.mutedForeground,
    fontWeight: "600",
  },
  miniTimelineLabelActive: {
    color: palette.foreground,
  },
  miniTimelineLabelCurrent: {
    color: palette.primary,
  },
  miniTimelineConnector: {
    width: 24,
    height: 2,
    borderRadius: 999,
    backgroundColor: palette.border,
  },
  miniTimelineConnectorDone: {
    backgroundColor: palette.mint,
  },
  timelineList: { gap: 10 },
  timelineRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  timelineRail: {
    width: 24,
    alignItems: "center",
  },
  timelineDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  timelineLine: {
    width: 2,
    minHeight: 30,
    marginTop: 4,
    backgroundColor: palette.border,
  },
  timelineCopy: {
    flex: 1,
    paddingBottom: 10,
    gap: 4,
  },
  timelineTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  timelineTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  currentBadge: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#FFE8F0",
  },
  currentBadgeText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
    color: palette.secondary,
  },
  timelineDescription: {
    fontSize: 13,
    lineHeight: 19,
    color: palette.mutedForeground,
  },
  timelineMeta: {
    fontSize: 12,
    lineHeight: 16,
    color: palette.mutedForeground,
  },
  detailLine: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  detailCopy: { flex: 1, gap: 2 },
  detailLabel: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    color: palette.primary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  detailValue: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  detailMeta: {
    fontSize: 12,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  riderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  riderAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
  },
  riderCopy: { flex: 1, gap: 2 },
  riderName: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  riderMeta: {
    fontSize: 12,
    lineHeight: 16,
    color: palette.mutedForeground,
  },
  riderHintText: {
    fontSize: 11,
    lineHeight: 15,
    color: palette.primary,
    fontWeight: "700",
  },
  riderActionButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
  },
  itemList: { gap: 12 },
  itemRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  itemImagePlaceholder: {
    width: 62,
    height: 62,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
  },
  itemCopy: { flex: 1, gap: 4 },
  itemTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  itemTitle: {
    flex: 1,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  itemPrice: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  itemQuantity: {
    fontSize: 12,
    lineHeight: 16,
    color: palette.mutedForeground,
  },
  summaryBlock: {
    gap: 10,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  summaryLabel: {
    fontSize: 14,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  summaryValue: {
    fontSize: 14,
    lineHeight: 18,
    color: palette.foreground,
  },
  summaryHighlight: {
    color: palette.successText,
  },
  summaryStrong: {
    fontWeight: "800",
    color: palette.foreground,
  },
  divider: {
    height: 1,
    backgroundColor: palette.border,
  },
  reviewComposer: { gap: 12 },
  reviewPrompt: {
    fontSize: 13,
    lineHeight: 19,
    color: palette.mutedForeground,
  },
  reviewStarsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  reviewStarButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
  },
  reviewInput: {
    minHeight: 104,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 18,
    backgroundColor: palette.surfaceMuted,
    fontSize: 14,
    lineHeight: 21,
    color: palette.foreground,
  },
  submitReviewButton: {
    minHeight: 52,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.secondary,
  },
  submitReviewButtonDisabled: {
    opacity: 0.55,
  },
  submitReviewButtonText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
    color: "#fff",
  },
  reviewDoneCard: {
    padding: 14,
    borderRadius: 18,
    backgroundColor: palette.successSurface,
    gap: 10,
  },
  reviewDoneBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: palette.surface,
  },
  reviewDoneBadgeText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
    color: palette.successText,
  },
  reviewDoneText: {
    fontSize: 13,
    lineHeight: 19,
    color: palette.foreground,
  },
  noteCard: {
    padding: 12,
    borderRadius: 16,
    backgroundColor: palette.surface,
    gap: 4,
  },
  noteLabel: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    color: palette.primary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  noteText: {
    fontSize: 13,
    lineHeight: 19,
    color: palette.foreground,
  },
  loadingWrap: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  loadingCard: {
    borderRadius: 24,
    backgroundColor: palette.surface,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  loadingText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
    color: palette.foreground,
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(20,18,24,0.38)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  modalCard: {
    width: "100%",
    maxWidth: 420,
    paddingHorizontal: 20,
    paddingVertical: 24,
    borderRadius: 28,
    backgroundColor: palette.surface,
    alignItems: "center",
    gap: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  modalIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.primarySoft,
  },
  modalTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "800",
    color: palette.foreground,
    textAlign: "center",
  },
  modalSubtitle: {
    fontSize: 14,
    lineHeight: 22,
    color: palette.mutedForeground,
    textAlign: "center",
  },
  modalActions: {
    width: "100%",
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  modalSecondaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
  },
  modalSecondaryButtonText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  modalPrimaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.foreground,
  },
  modalPrimaryButtonText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: "#fff",
  },
});
