import { StyleSheet } from "react-native";

import { palette } from "@/src/theme/palette";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: palette.background },
  content: { paddingBottom: 42, gap: 22 },
  header: {
    paddingHorizontal: 20,
    paddingTop: 8,
    gap: 8,
  },
  kicker: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
    color: palette.sky,
  },
  title: {
    fontSize: 31,
    lineHeight: 37,
    fontWeight: "800",
    color: palette.foreground,
  },
  subtitle: {
    fontSize: 15,
    lineHeight: 23,
    fontWeight: "500",
    color: palette.mutedForeground,
    maxWidth: "92%",
  },
  section: { gap: 10 },
  sectionHeader: {
    paddingHorizontal: 20,
    gap: 3,
  },
  sectionTitle: {
    fontSize: 21,
    lineHeight: 27,
    fontWeight: "800",
    color: palette.foreground,
  },
  sectionSubtitle: {
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "500",
    color: palette.mutedForeground,
  },
  cardList: { paddingHorizontal: 20, gap: 10 },
  orderCard: {
    position: "relative",
    padding: 14,
    borderRadius: 22,
    backgroundColor: palette.surface,
    gap: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 0.72,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  orderCardActive: {
    backgroundColor: "#FFF9F5",
    borderWidth: 1,
    borderColor: "#FFD7C3",
    shadowColor: "rgba(255, 122, 89, 0.2)",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.9,
    shadowRadius: 16,
    elevation: 5,
  },
  orderTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  orderCopy: { flex: 1, gap: 2 },
  orderRestaurant: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "800",
    color: palette.foreground,
  },
  orderMeta: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  statusPill: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  statusPillText: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "700",
  },
  orderItemsWrap: { display: "none", gap: 4 },
  orderItemLine: { fontSize: 13, lineHeight: 18, color: palette.foreground },
  orderMoreItems: { fontSize: 12, lineHeight: 16, color: palette.mutedForeground },
  activeProgressCard: {
    borderRadius: 16,
    backgroundColor: "#FFFDFE",
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 7,
    borderWidth: 1,
    borderColor: "#F7D7E3",
  },
  activeProgressTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  activeProgressAmountRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  activeOpenCue: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFEAF3",
  },
  activeProgressChip: {
    maxWidth: "64%",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 999,
    backgroundColor: "#FFEAF3",
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  activeProgressChipText: {
    flexShrink: 1,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
    color: palette.secondary,
  },
  activeProgressTrack: {
    width: "100%",
    height: 6,
    borderRadius: 999,
    backgroundColor: "#F7DDE7",
    overflow: "hidden",
  },
  activeProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: palette.secondary,
  },
  activeDestinationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  orderBottomRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 10,
  },
  orderBottomLeft: {
    flex: 1,
    gap: 6,
  },
  orderAddressWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  orderAddress: { fontSize: 12, lineHeight: 17, color: palette.mutedForeground, flex: 1 },
  orderTotal: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "800",
    color: palette.foreground,
  },
  orderTrailingMeta: {
    alignItems: "flex-end",
    justifyContent: "flex-end",
    gap: 6,
  },
  reorderButton: {
    minHeight: 36,
    borderRadius: 999,
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    backgroundColor: "#FFEAF3",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  reorderButtonDisabled: {
    opacity: 0.7,
  },
  reorderButtonText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.secondary,
  },
  loadMoreButton: {
    minHeight: 44,
    borderRadius: 999,
    backgroundColor: "#FFEAF3",
    borderWidth: 1,
    borderColor: "#F8C5D8",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  loadMoreButtonDisabled: {
    opacity: 0.72,
  },
  loadMoreButtonText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.secondary,
  },
  loadingWrap: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  inlineLoadingWrap: {
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  inlineEmptyWrap: {
    paddingHorizontal: 20,
    paddingTop: 8,
    alignItems: "center",
    gap: 10,
  },
  loadingCard: {
    paddingHorizontal: 22,
    paddingVertical: 24,
    borderRadius: 30,
    backgroundColor: palette.surface,
    alignItems: "center",
    gap: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  loadingIndicatorWrap: {
    width: 62,
    height: 62,
    borderRadius: 31,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.primarySoft,
  },
  loadingTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "800",
    color: palette.foreground,
  },
  loadingText: {
    fontSize: 14,
    lineHeight: 22,
    color: palette.mutedForeground,
    textAlign: "center",
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    gap: 10,
  },
  emptyAnimation: {
    width: 190,
    height: 190,
  },
});
