import { StyleSheet } from "react-native";

import { palette } from "@/src/theme/palette";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  content: {
    gap: 14,
    paddingBottom: 32,
  },
  header: {
    paddingHorizontal: 18,
    paddingTop: 8,
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  orderHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    minWidth: 0,
  },
  restaurantHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  restaurantLogoWrap: {
    width: 44,
    height: 44,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: palette.surfaceMuted,
  },
  restaurantLogo: {
    width: "100%",
    height: "100%",
  },
  restaurantLogoFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.primarySoft,
  },
  restaurantHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  detailsButton: {
    minHeight: 46,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: palette.secondary,
    borderWidth: 1,
    borderColor: palette.secondary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    shadowColor: palette.secondary,
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  detailsButtonFull: {
    width: "100%",
  },
  detailsButtonText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    color: "#fff",
  },
  liveBadge: {
    minHeight: 38,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  liveBadgeText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: palette.primary,
  },
  liveBadgeTextLive: {
    color: palette.secondary,
  },
  kicker: {
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "800",
    letterSpacing: 0,
    textTransform: "uppercase",
    color: palette.secondary,
  },
  title: {
    fontSize: 19,
    lineHeight: 24,
    fontWeight: "800",
    color: palette.foreground,
  },
  subtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  headerMetaRow: {
    marginHorizontal: 18,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    flexWrap: "wrap",
  },
  orderIdPill: {
    minHeight: 36,
    paddingHorizontal: 0,
    borderRadius: 0,
    backgroundColor: "transparent",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  orderIdText: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "800",
    color: palette.foreground,
  },
  detailsButtonRow: {
    marginHorizontal: 18,
  },
  quickStatusRow: {
    marginHorizontal: 18,
    flexDirection: "row",
    gap: 10,
  },
  summaryCard: {
    marginHorizontal: 18,
    padding: 16,
    borderRadius: 26,
    backgroundColor: palette.surface,
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.9,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  summaryHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  summaryTitle: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "800",
    color: palette.foreground,
  },
  summaryHint: {
    fontSize: 12,
    lineHeight: 16,
    color: palette.mutedForeground,
    fontWeight: "600",
  },
  statusPill: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  statusPillDefault: {
    backgroundColor: palette.primarySoft,
  },
  statusPillLive: {
    backgroundColor: "#EEF4FF",
  },
  statusPillSuccess: {
    backgroundColor: palette.successSurface,
  },
  statusPillText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
    color: palette.primary,
  },
  statusPillTextLive: {
    color: palette.sky,
  },
  statusPillTextSuccess: {
    color: palette.successText,
  },
  progressTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: palette.surfaceMuted,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
  },
  summaryFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  summaryFooterChip: {
    flex: 1,
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: palette.surfaceMuted,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  summaryFooterChipWarning: {
    backgroundColor: "#FFF7ED",
  },
  summaryFooterText: {
    fontSize: 12,
    lineHeight: 16,
    color: palette.mutedForeground,
    fontWeight: "600",
  },
  summaryFooterTextWarning: {
    color: "#92400E",
  },
  networkHint: {
    marginHorizontal: 18,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    gap: 10,
  },
  networkHintLive: {
    backgroundColor: "#F8F1FF",
    borderColor: "#EBD9FF",
  },
  networkHintStale: {
    backgroundColor: "#FFF7ED",
    borderColor: "#F6D6A5",
  },
  networkHintCopy: {
    flex: 1,
    gap: 2,
  },
  networkHintTitle: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  networkHintSubtitle: {
    fontSize: 12,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  offlineNoticeWrap: {
    marginHorizontal: 18,
  },
  refundNoticeCard: {
    marginHorizontal: 18,
    padding: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#F8C6DA",
    backgroundColor: "#FFF3F8",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  refundNoticeIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFE2EF",
  },
  refundNoticeCopy: {
    flex: 1,
    gap: 3,
  },
  refundNoticeTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  refundNoticeText: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  trackingCard: {
    marginHorizontal: 18,
    borderRadius: 28,
    overflow: "hidden",
  },
  deliveredSummaryCard: {
    marginHorizontal: 18,
    borderRadius: 22,
    backgroundColor: palette.surface,
    paddingHorizontal: 12,
    paddingVertical: 11,
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(248, 90, 147, 0.14)",
    shadowColor: "#F85A93",
    shadowOpacity: 0.14,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  deliveredSummaryTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  deliveredSummaryCopy: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  deliveredSummaryIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFEAF3",
  },
  deliveredSummaryTextWrap: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  deliveredSummaryTitle: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "800",
    color: palette.foreground,
  },
  deliveredSummaryMeta: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  deliveredSummaryTotalBox: {
    alignItems: "flex-end",
    gap: 2,
  },
  deliveredSummaryTotalLabel: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.7,
    color: palette.mutedForeground,
  },
  deliveredSummaryTotalValue: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900",
    color: palette.foreground,
  },
  deliveredReorderButton: {
    minHeight: 30,
    borderRadius: 999,
    backgroundColor: palette.secondary,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    marginTop: 3,
    shadowColor: palette.secondary,
    shadowOpacity: 0.16,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  deliveredReorderButtonDisabled: {
    opacity: 0.72,
  },
  deliveredReorderButtonText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    color: "#fff",
  },
  journeyCard: {
    marginHorizontal: 18,
    borderRadius: 22,
    backgroundColor: palette.surface,
    paddingHorizontal: 15,
    paddingVertical: 14,
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.72,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  journeyTitle: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "800",
    color: palette.foreground,
  },
  journeyHint: {
    fontSize: 12,
    lineHeight: 16,
    color: palette.mutedForeground,
  },
  journeyRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  journeyStep: {
    flex: 1,
    gap: 8,
  },
  journeyMarkerRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  journeyMarker: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
    borderWidth: 1,
    borderColor: "#E7DAD3",
  },
  journeyMarkerDone: {
    backgroundColor: palette.secondary,
    borderColor: palette.secondary,
  },
  journeyMarkerCurrent: {
    backgroundColor: "#FFF7FA",
    borderColor: palette.secondary,
  },
  journeyMarkerText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: palette.mutedForeground,
  },
  journeyMarkerTextOnSolid: {
    color: "#fff",
  },
  journeyMarkerTextCurrent: {
    color: palette.secondary,
  },
  journeyLine: {
    flex: 1,
    height: 2,
    marginHorizontal: 6,
    backgroundColor: "#EADFD9",
  },
  journeyLineDone: {
    backgroundColor: palette.secondary,
  },
  journeyStepLabel: {
    fontSize: 11,
    lineHeight: 15,
    color: palette.mutedForeground,
    fontWeight: "700",
    maxWidth: 58,
  },
  journeyStepLabelActive: {
    color: palette.foreground,
  },
  waitingCard: {
    minHeight: 300,
    borderRadius: 28,
    backgroundColor: "#F3F7FF",
    paddingHorizontal: 20,
    paddingVertical: 18,
    alignItems: "center",
    gap: 10,
  },
  waitingPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#FFFFFFCC",
  },
  waitingPillText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    color: palette.sky,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  waitingSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: palette.mutedForeground,
    textAlign: "center",
    maxWidth: 280,
  },
  waitingAnimation: {
    width: "100%",
    height: 200,
  },
  confirmedCard: {
    minHeight: 288,
    borderRadius: 28,
    backgroundColor: "#EEF4FF",
    paddingHorizontal: 20,
    paddingVertical: 18,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  confirmedPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#FFFFFFCC",
  },
  confirmedPillText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    color: palette.sky,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  confirmedSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: palette.mutedForeground,
    textAlign: "center",
    maxWidth: 280,
  },
  prepEtaCallout: {
    minWidth: 156,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFFCC",
    gap: 2,
  },
  prepEtaTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "800",
    color: palette.foreground,
  },
  prepEtaSubtitle: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  confirmedBadge: {
    width: 86,
    height: 86,
    borderRadius: 43,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFFB8",
  },
  preparingCard: {
    minHeight: 304,
    borderRadius: 28,
    backgroundColor: "#FFF3D6",
    paddingHorizontal: 20,
    paddingVertical: 18,
    alignItems: "center",
    gap: 10,
  },
  preparingPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#FFFFFFCC",
  },
  preparingPillText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    color: "#9A4F00",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  preparingAnimation: {
    width: "100%",
    height: 190,
  },
  preparingRange: {
    fontSize: 28,
    lineHeight: 30,
    fontWeight: "800",
    color: "#9A4F00",
  },
  preparingRangeMeta: {
    maxWidth: 280,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "600",
    color: palette.mutedForeground,
    textAlign: "center",
  },
  supportButton: {
    minHeight: 38,
    marginTop: 4,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: "#FFFFFFD9",
    borderWidth: 1,
    borderColor: "#F3D2E0",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  supportButtonText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  readyPickupCard: {
    minHeight: 304,
    borderRadius: 28,
    backgroundColor: "#FFF6F1",
    paddingHorizontal: 20,
    paddingVertical: 18,
    alignItems: "center",
    gap: 10,
  },
  readyPickupPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#FFFFFFCC",
  },
  readyPickupPillText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    color: palette.primary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  readyPickupSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: palette.mutedForeground,
    textAlign: "center",
    maxWidth: 290,
  },
  readyPickupAssignedChip: {
    width: "100%",
    position: "relative",
    borderRadius: 22,
    paddingLeft: 14,
    paddingRight: 12,
    paddingVertical: 12,
    backgroundColor: "rgba(255, 255, 255, 0.72)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.86)",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowColor: "#F85A93",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  readyPickupAssignedLeft: {
    flex: 8,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  readyPickupAssignedAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 232, 240, 0.95)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.9)",
  },
  readyPickupAssignedCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  readyPickupAssignedMetaRow: {
    flex: 1,
    minWidth: 0,
    position: "relative",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  readyPickupAssignedLabel: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    color: palette.primary,
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  readyPickupAssignedValue: {
    flexShrink: 1,
    minWidth: 0,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  readyPickupAssignedPhone: {
    flexShrink: 1,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
    color: palette.mutedForeground,
  },
  readyPickupAssignedDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#D7C8C0",
  },
  readyPickupAnimation: {
    width: "100%",
    height: 190,
  },
  readyPickupMeta: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "700",
    color: palette.foreground,
    textAlign: "center",
  },
  pickupWaitingCard: {
    minHeight: 320,
    borderRadius: 28,
    backgroundColor: "#FFF6F1",
    paddingHorizontal: 20,
    paddingVertical: 20,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  pickupWaitingPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#FFFFFFCC",
  },
  pickupWaitingPillText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    color: palette.primary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  pickupWaitingAnimation: {
    width: "100%",
    height: 170,
  },
  pickupWaitingTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "800",
    color: palette.foreground,
    textAlign: "center",
  },
  pickupWaitingSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: palette.mutedForeground,
    textAlign: "center",
    maxWidth: 300,
  },
  pickupWaitingMeta: {
    fontSize: 12,
    lineHeight: 18,
    color: palette.primary,
    fontWeight: "700",
    textAlign: "center",
  },
  stateCard: {
    minHeight: 240,
    borderRadius: 28,
    paddingHorizontal: 24,
    paddingVertical: 24,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  stateIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
  },
  stateTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "800",
    color: palette.foreground,
    textAlign: "center",
  },
  stateSubtitle: {
    fontSize: 14,
    lineHeight: 22,
    color: palette.mutedForeground,
    textAlign: "center",
  },
  routeCard: {
    marginHorizontal: 18,
    borderRadius: 22,
    backgroundColor: palette.surface,
    padding: 16,
    gap: 14,
    shadowColor: palette.shadow,
    shadowOpacity: 0.75,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  routeHeader: {
    gap: 2,
  },
  routeTitle: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "800",
    color: palette.foreground,
  },
  routeSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  routeSteps: {
    flexDirection: "row",
    gap: 10,
  },
  routeRail: {
    width: 18,
    alignItems: "center",
    paddingTop: 6,
  },
  routeDotPrimary: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: palette.primary,
  },
  routeLine: {
    width: 2,
    flex: 1,
    marginVertical: 6,
    backgroundColor: "#F0E7DF",
  },
  routeDotSecondary: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: palette.secondary,
  },
  routeStops: {
    flex: 1,
    gap: 14,
  },
  routeStop: {
    gap: 2,
  },
  routeStopLabel: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    color: palette.primary,
  },
  routeStopTitle: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
    color: palette.foreground,
  },
  routeStopMeta: {
    fontSize: 12,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  infoGrid: {
    marginHorizontal: 18,
    gap: 10,
  },
  infoCard: {
    borderRadius: 22,
    backgroundColor: palette.surface,
    padding: 14,
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.75,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  infoCardHalf: {
    marginHorizontal: 0,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  infoCopy: {
    flex: 1,
    gap: 2,
  },
  infoMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  infoMetaFlexible: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    color: palette.primary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  infoValue: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
    color: palette.foreground,
  },
  infoMeta: {
    fontSize: 12,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  callButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF7FA",
    borderWidth: 1,
    borderColor: "#F3D2E0",
  },
  readyPickupCallButton: {
    flex: 2,
    maxWidth: 52,
    minWidth: 46,
    alignSelf: "center",
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 232, 240, 0.95)",
    borderWidth: 1,
    borderColor: "rgba(248, 90, 147, 0.16)",
  },
  reviewCard: {
    marginHorizontal: 18,
    backgroundColor: palette.surface,
    borderRadius: 22,
    padding: 15,
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.68,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  reviewHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  reviewTitle: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "800",
    color: palette.foreground,
  },
  reviewHint: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  reviewDoneBadge: {
    minHeight: 34,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "#FFF7ED",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  reviewDoneBadgeText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: "#B45309",
  },
  reviewDoneText: {
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "600",
    color: palette.foreground,
  },
  reviewStarsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  reviewStarButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
  },
  reviewInput: {
    minHeight: 84,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.background,
    paddingHorizontal: 13,
    paddingVertical: 11,
    fontSize: 14,
    lineHeight: 19,
    color: palette.foreground,
    fontWeight: "600",
  },
  submitReviewButton: {
    minHeight: 48,
    borderRadius: 999,
    backgroundColor: palette.foreground,
    alignItems: "center",
    justifyContent: "center",
  },
  submitReviewButtonDisabled: {
    opacity: 0.48,
  },
  submitReviewButtonText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
    color: palette.background,
  },
  actionsCard: {
    marginHorizontal: 18,
    backgroundColor: palette.surface,
    borderRadius: 22,
    padding: 14,
    gap: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 0.75,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  cancelButton: {
    minHeight: 46,
    borderRadius: 999,
    backgroundColor: "#FFF7FA",
    borderWidth: 1,
    borderColor: "#F3D2E0",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  cancelButtonDisabled: {
    opacity: 0.56,
  },
  cancelButtonText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.primary,
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: 999,
    backgroundColor: palette.foreground,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  primaryButtonText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
    color: palette.background,
  },
  secondaryButton: {
    minHeight: 46,
    borderRadius: 999,
    backgroundColor: palette.surfaceMuted,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  secondaryButtonText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  loadingWrap: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  loadingCard: {
    borderRadius: 28,
    backgroundColor: palette.surface,
    paddingHorizontal: 22,
    paddingVertical: 24,
    alignItems: "center",
    gap: 10,
  },
  loadingPanel: {
    marginHorizontal: 18,
    marginTop: 4,
    borderRadius: 24,
    backgroundColor: palette.surface,
    paddingHorizontal: 16,
    paddingVertical: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.72,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  loadingCopy: {
    flex: 1,
    gap: 2,
  },
  loadingTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "800",
    color: palette.foreground,
  },
  loadingText: {
    fontSize: 14,
    lineHeight: 22,
    color: palette.mutedForeground,
  },
  emptyWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(15, 23, 42, 0.38)",
  },
  modalBackdropTouch: {
    ...StyleSheet.absoluteFillObject,
  },
  cancelModalCard: {
    margin: 18,
    borderRadius: 26,
    backgroundColor: palette.surface,
    padding: 18,
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.9,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  cancelModalIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#FFF7FA",
    alignItems: "center",
    justifyContent: "center",
  },
  cancelModalTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "800",
    color: palette.foreground,
  },
  cancelModalSubtitle: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  cancelModalActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  cancelModalSecondary: {
    flex: 1,
    minHeight: 48,
    borderRadius: 999,
    backgroundColor: palette.surfaceMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelModalSecondaryText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  cancelModalPrimary: {
    flex: 1,
    minHeight: 48,
    borderRadius: 999,
    backgroundColor: palette.foreground,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelModalPrimaryText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.background,
  },
  trackingSkeletonWrap: {
    gap: 14,
  },
  trackingSkeletonMap: {
    height: 280,
    borderRadius: 30,
  },
  detailsSheet: {
    maxHeight: "82%",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: palette.surface,
    paddingHorizontal: 18,
    paddingTop: 10,
    shadowColor: "#000",
    shadowOpacity: 0.14,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: -8 },
    elevation: 10,
  },
  detailsHandle: {
    alignSelf: "center",
    width: 42,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#E7DAD3",
    marginBottom: 12,
  },
  detailsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  detailsTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "800",
    color: palette.foreground,
  },
  detailsSubtitle: {
    fontSize: 12,
    lineHeight: 17,
    color: palette.mutedForeground,
    fontWeight: "600",
  },
  detailsDateText: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 16,
    color: palette.secondary,
    fontWeight: "800",
  },
  detailsCloseButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
  },
  detailsList: {
    flex: 1,
    maxHeight: 520,
  },
  detailsBottomSheetContent: {
    flex: 1,
    paddingBottom: 0,
  },
  detailsTimelineCard: {
    borderRadius: 20,
    backgroundColor: palette.background,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 10,
    gap: 10,
  },
  detailsTimelineTitle: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "800",
    color: palette.foreground,
  },
  detailsTimelineRow: {
    paddingRight: 4,
  },
  detailsTimelineStep: {
    width: 88,
    gap: 7,
  },
  detailsTimelineLine: {
    width: 50,
    height: 2,
    marginHorizontal: 6,
    backgroundColor: "#EADFD9",
  },
  detailsTimelineLabel: {
    maxWidth: 76,
    fontSize: 11,
    lineHeight: 14,
    color: palette.mutedForeground,
    fontWeight: "700",
  },
  detailsTimelineTime: {
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "700",
    color: palette.mutedForeground,
  },
  detailsItemRow: {
    minHeight: 62,
    borderRadius: 18,
    backgroundColor: palette.background,
    paddingHorizontal: 12,
    paddingVertical: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 9,
  },
  detailsItemIcon: {
    width: 36,
    height: 36,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.primarySoft,
  },
  detailsItemCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  detailsItemTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  detailsItemName: {
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "800",
    color: palette.foreground,
  },
  detailsItemPrice: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  detailsItemMeta: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  detailsDivider: {
    height: 1,
    backgroundColor: palette.border,
    marginVertical: 10,
  },
  paymentSummary: {
    borderRadius: 20,
    backgroundColor: palette.background,
    padding: 14,
    gap: 10,
  },
  paymentRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  paymentLabel: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  paymentValue: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  paymentDiscount: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.successText,
  },
  paymentValueStrong: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "900",
    color: palette.foreground,
  },
});
