import { StyleSheet } from "react-native";

import { palette } from "@/src/theme/palette";

export const styles = StyleSheet.create({
  centerState: { flex: 1, justifyContent: "center", paddingHorizontal: 20 },
  centerStateText: {
    marginTop: 10,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
    color: palette.mutedForeground,
    textAlign: "center",
  },
  listContent: { paddingBottom: 44 },
  listContentWithCart: { paddingBottom: 210 },
  hero: {
    height: 188,
    marginHorizontal: 20,
    marginTop: 8,
    borderRadius: 34,
    overflow: "hidden",
    backgroundColor: palette.surfaceMuted,
  },
  heroImageWrap: { ...StyleSheet.absoluteFillObject },
  heroImage: { width: "100%", height: "100%" },
  heroFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
  },
  heroShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(19, 24, 38, 0.18)",
  },
  heroTopRow: {
    position: "absolute",
    top: 14,
    left: 14,
    right: 14,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  heroActionGroup: { flexDirection: "row", gap: 10 },
  heroButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.92)",
  },
  heroBottomRow: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  statePill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.94)",
  },
  statePillClosed: { backgroundColor: "rgba(231, 139, 39, 0.92)" },
  statePillText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.foreground,
  },
  statePillTextClosed: { color: palette.surface },
  offerPillButton: {
    maxWidth: "58%",
    backgroundColor: "rgba(255,99,146,0.88)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  offerPillText: {
    flexShrink: 1,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.surface,
  },
  infoCard: {
    marginHorizontal: 20,
    marginTop: -18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 30,
    backgroundColor: palette.surface,
    gap: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  infoTopRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  restaurantLogo: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: palette.surfaceMuted,
  },
  restaurantLogoFallback: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
  },
  infoCopy: { flex: 1, gap: 4 },
  title: { fontSize: 22, lineHeight: 28, fontWeight: "800", color: palette.foreground },
  inlineOfferRow: {
    paddingRight: 8,
    gap: 8,
  },
  inlineOfferChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#FFEAF1",
  },
  inlineOfferText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    color: palette.secondary,
  },
  subtitle: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    color: palette.mutedForeground,
  },
  infoBadgeRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  serviceabilityCard: {
    marginHorizontal: 20,
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 24,
    backgroundColor: "#FFF0F6",
    borderWidth: 1,
    borderColor: "#FFD7E5",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  serviceabilityIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
  },
  serviceabilityCopy: {
    flex: 1,
    gap: 4,
  },
  serviceabilityTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  serviceabilityBody: {
    fontSize: 12,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  serviceabilityActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  serviceabilityAction: {
    minHeight: 34,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: "center",
    justifyContent: "center",
  },
  serviceabilityActionPrimary: {
    backgroundColor: palette.secondary,
    borderColor: palette.secondary,
  },
  serviceabilityActionText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: palette.foreground,
  },
  serviceabilityActionPrimaryText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: palette.surface,
  },
  factChip: {
    minWidth: "47%",
    flex: 1,
    minHeight: 56,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: palette.surfaceMuted,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  factChipPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.99 }],
  },
  factChipIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFEAF3",
  },
  factChipCopy: {
    flex: 1,
    gap: 2,
  },
  factChipLabel: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    color: palette.mutedForeground,
    textTransform: "uppercase",
  },
  factChipValue: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "800",
    color: palette.foreground,
  },
  reviewPreviewSection: {
    paddingHorizontal: 20,
    paddingTop: 8,
    gap: 10,
  },
  reviewEntryCard: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 22,
    backgroundColor: palette.surface,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.45,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  reviewEntryIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFEAF3",
  },
  reviewEntryCopy: {
    flex: 1,
    gap: 3,
  },
  reviewEntryTitle: {
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
    color: palette.foreground,
  },
  reviewEntrySubtitle: {
    fontSize: 12,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  offerProgressCard: {
    marginBottom: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 24,
    backgroundColor: palette.surface,
    gap: 8,
    shadowColor: palette.shadow,
    shadowOpacity: 0.14,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  offerProgressCardUnlocked: { backgroundColor: "#EFFAF5" },
  offerProgressHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  offerProgressBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  offerProgressBadgeText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    color: palette.secondary,
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  offerProgressBadgeTextUnlocked: {
    color: palette.successText,
  },
  offerProgressValue: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.foreground,
  },
  offerProgressTitle: { fontSize: 14, lineHeight: 18, fontWeight: "800", color: palette.foreground },
  offerProgressSubtitle: {
    fontSize: 12,
    lineHeight: 16,
    color: palette.mutedForeground,
  },
  offerTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "#F5E1D6",
    overflow: "hidden",
    marginTop: 2,
  },
  offerFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: palette.secondary,
  },
  offerFillUnlocked: {
    backgroundColor: palette.successText,
  },
  menuIntro: { paddingHorizontal: 20, paddingTop: 22, gap: 2 },
  menuKicker: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    letterSpacing: 0.9,
    textTransform: "uppercase",
    color: palette.secondary,
  },
  menuSectionTitle: { fontSize: 24, lineHeight: 30, fontWeight: "800", color: palette.foreground },
  menuSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    color: palette.mutedForeground,
  },
  controlsWrap: {
    marginTop: 8,
    paddingTop: 8,
    paddingBottom: 4,
  },
  overlayWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 40,
  },
  overlayBar: {
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: "rgba(255,250,247,0.98)",
    borderBottomWidth: 1,
    borderBottomColor: "#F0E2D8",
    shadowColor: palette.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  searchOverlayWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 45,
  },
  searchOverlaySurface: {
    flex: 1,
    backgroundColor: "rgba(255,250,247,0.98)",
  },
  searchOverlayHeader: {
    paddingTop: 8,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#F0E2D8",
    backgroundColor: "rgba(255,250,247,0.98)",
  },
  searchHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 20,
  },
  searchBackButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: "#F0E2D8",
  },
  searchHeaderField: {
    flex: 1,
  },
  searchResultsContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 32,
    gap: 12,
  },
  searchResultsContentEmpty: {
    paddingTop: 10,
  },
  searchResultCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 22,
    backgroundColor: palette.surface,
    shadowColor: palette.shadow,
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  searchResultCardMuted: {
    opacity: 0.72,
  },
  searchResultMedia: {
    width: 58,
    height: 58,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: palette.surfaceMuted,
  },
  searchResultImage: {
    width: "100%",
    height: "100%",
  },
  searchResultImageFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
  },
  searchResultCopy: {
    flex: 1,
    gap: 4,
  },
  searchResultTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  searchResultTitle: {
    flex: 1,
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
    color: palette.foreground,
  },
  searchPopularBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    minHeight: 22,
    borderRadius: 999,
    backgroundColor: "#FFF1E2",
  },
  searchPopularBadgeText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    color: palette.secondary,
  },
  searchResultMeta: {
    fontSize: 12,
    lineHeight: 16,
    color: palette.mutedForeground,
  },
  searchResultPrice: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "700",
    color: palette.secondary,
  },
  searchResultAction: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.secondary,
  },
  searchResultActionDisabled: {
    backgroundColor: palette.surfaceMuted,
  },
  searchResultQuantityWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  searchResultStepButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
  },
  searchResultStepButtonPrimary: {
    backgroundColor: palette.secondary,
  },
  searchResultQuantityText: {
    minWidth: 18,
    textAlign: "center",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "800",
    color: palette.foreground,
  },
  searchEmptyCard: {
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 24,
    paddingVertical: 28,
    borderRadius: 28,
    backgroundColor: palette.surface,
  },
  searchEmptyIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1F6",
  },
  searchEmptyTitle: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "800",
    color: palette.foreground,
  },
  searchEmptySubtitle: {
    fontSize: 13,
    lineHeight: 19,
    color: palette.mutedForeground,
    textAlign: "center",
  },
  controlsStack: {
    gap: 10,
  },
  emptyIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1F6",
    marginBottom: 10,
  },
  menuSearchWrap: {
    marginHorizontal: 20,
    minHeight: 44,
    borderRadius: 18,
    paddingHorizontal: 14,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: "#F0E2D8",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  menuSearchWrapFlush: {
    marginHorizontal: 0,
  },
  menuSearchInput: {
    flex: 1,
    paddingVertical: 10,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
    color: palette.foreground,
  },
  menuSearchClear: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
  },
  categoryRow: { paddingHorizontal: 20, paddingRight: 32, gap: 8 },
  categoryChip: {
    minHeight: 30,
    paddingHorizontal: 11,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
    backgroundColor: "#FFFBF8",
    borderWidth: 1,
    borderColor: "#F3E3D8",
    shadowColor: palette.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  categoryChipIndicator: {
    width: 5,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#E4D0C5",
  },
  categoryChipIndicatorActive: {
    backgroundColor: "#FFD86B",
  },
  categoryChipActive: {
    backgroundColor: "#1E1B24",
    borderColor: "#1E1B24",
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  categoryChipText: { fontSize: 12, lineHeight: 15, fontWeight: "800", color: "#7A6B62" },
  categoryChipTextActive: { color: palette.surface },
  sectionWrap: { paddingTop: 0, gap: 6 },
  sectionHeader: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 8, gap: 4 },
  sectionTitleRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  sectionHeaderTitle: { fontSize: 20, lineHeight: 25, fontWeight: "800", color: palette.foreground },
  sectionHeaderSubtitle: { fontSize: 13, lineHeight: 18, color: palette.mutedForeground },
  popularRow: { paddingHorizontal: 20, gap: 14, paddingRight: 28 },
  popularCard: {
    width: 184,
    padding: 12,
    borderRadius: 24,
    backgroundColor: palette.surface,
    gap: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  popularCardMuted: { opacity: 0.72 },
  popularImage: { width: "100%", height: 110, borderRadius: 18, backgroundColor: palette.surfaceMuted },
  popularImageFallback: { width: "100%", height: 110, borderRadius: 18, backgroundColor: palette.surfaceMuted },
  popularMetaBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#FFF0E5",
  },
  popularMetaBadgeText: { fontSize: 11, lineHeight: 14, fontWeight: "700", color: palette.primary },
  popularTitle: { fontSize: 15, lineHeight: 19, fontWeight: "800", color: palette.foreground },
  popularDescription: { fontSize: 12, lineHeight: 16, color: palette.mutedForeground },
  popularFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  popularPriceBlock: { flex: 1, gap: 2 },
  popularPrice: { fontSize: 13, lineHeight: 17, fontWeight: "700", color: palette.foreground },
  popularAddButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.secondary,
  },
  popularQuantityControl: {
    minWidth: 96,
    height: 36,
    paddingHorizontal: 4,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFEAF3",
  },
  popularIconButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
  },
  popularIconButtonPrimary: { backgroundColor: palette.secondary },
  popularQuantityText: { minWidth: 20, textAlign: "center", fontSize: 13, lineHeight: 17, fontWeight: "700", color: palette.foreground },
  menuItemWrap: { paddingHorizontal: 20, paddingBottom: 12 },
  menuCard: {
    flexDirection: "row",
    gap: 14,
    padding: 14,
    borderRadius: 24,
    backgroundColor: palette.surface,
    shadowColor: palette.shadow,
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  menuCardMuted: { opacity: 0.72 },
  menuCardCopy: { flex: 1, gap: 8 },
  menuMetaRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  metaBadge: { paddingHorizontal: 8, paddingVertical: 6, borderRadius: 999, backgroundColor: palette.surfaceMuted },
  metaBadgePopular: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: "#FFF0E5" },
  metaBadgeText: { fontSize: 11, lineHeight: 14, fontWeight: "700", color: palette.foreground },
  metaBadgeTextPopular: { color: palette.primary },
  titleBlock: { gap: 4 },
  menuItemTitle: { fontSize: 17, lineHeight: 22, fontWeight: "800", color: palette.foreground },
  menuDescription: { fontSize: 13, lineHeight: 18, fontWeight: "500", color: palette.mutedForeground },
  menuPriceRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  menuPrice: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: palette.foreground },
  mediaColumn: { width: 96, alignItems: "flex-end", justifyContent: "flex-start", gap: 12 },
  menuImage: { width: 96, height: 88, borderRadius: 18, backgroundColor: palette.surfaceMuted },
  menuImageFallback: { width: 96, height: 88, borderRadius: 18, backgroundColor: palette.surfaceMuted },
  singleAddButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.secondary,
  },
  singleAddButtonDisabled: { backgroundColor: palette.surfaceMuted },
  quantityControl: {
    minWidth: 96,
    height: 36,
    borderRadius: 999,
    paddingHorizontal: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFEAF3",
  },
  iconButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
  },
  iconButtonPrimary: { backgroundColor: palette.secondary },
  iconButtonDisabled: { backgroundColor: palette.surfaceMuted },
  quantityText: { minWidth: 20, textAlign: "center", fontSize: 13, lineHeight: 17, fontWeight: "700", color: palette.foreground },
  emptyCard: {
    marginHorizontal: 20,
    marginTop: 18,
    paddingHorizontal: 20,
    paddingVertical: 24,
    borderRadius: 28,
    alignItems: "center",
    gap: 8,
    backgroundColor: palette.surface,
  },
  emptyTitle: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: palette.foreground },
  emptySubtitle: { fontSize: 14, lineHeight: 20, color: palette.mutedForeground, textAlign: "center" },
  cartBarWrap: { position: "absolute", left: 20, right: 20, bottom: 0 },
  cartBarLift: {
    borderRadius: 28,
    shadowColor: "#111827",
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 9 },
    elevation: 6,
  },
  cartBar: {
    overflow: "hidden",
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingVertical: 14,
    backgroundColor: palette.secondary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cartBarGlow: {
    position: "absolute",
    top: -28,
    right: -20,
    width: 118,
    height: 118,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  cartBarSheen: {
    position: "absolute",
    left: 20,
    right: 20,
    top: 1,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.38)",
  },
  cartBarCopy: { flex: 1, gap: 2 },
  cartBarTitle: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: palette.surface },
  cartBarSubtitle: { fontSize: 12, lineHeight: 16, color: "rgba(255,255,255,0.84)" },
  cartBarAction: { flexDirection: "row", alignItems: "center", gap: 6 },
  cartBarActionText: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: palette.surface },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 60,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(22, 27, 38, 0.38)",
    paddingHorizontal: 20,
  },
  modalCard: {
    width: "100%",
    maxWidth: 360,
    padding: 20,
    borderRadius: 28,
    backgroundColor: palette.surface,
    gap: 14,
    overflow: "hidden",
  },
  modalGlow: {
    position: "absolute",
    top: -42,
    right: -26,
    width: 132,
    height: 132,
    borderRadius: 66,
    backgroundColor: "rgba(255, 99, 146, 0.16)",
  },
  modalBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "#FFE8F0",
  },
  modalBadgeText: { fontSize: 11, lineHeight: 14, fontWeight: "700", color: palette.secondary },
  modalTitle: { fontSize: 22, lineHeight: 28, fontWeight: "800", color: palette.foreground },
  modalText: { fontSize: 14, lineHeight: 21, color: palette.mutedForeground },
  modalPreviewRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 10,
    borderRadius: 18,
    backgroundColor: palette.surfaceMuted,
  },
  modalPreviewImage: { width: 54, height: 54, borderRadius: 14, backgroundColor: palette.surface },
  modalPreviewImageFallback: { width: 54, height: 54, borderRadius: 14, backgroundColor: palette.surface },
  modalPreviewCopy: { flex: 1, gap: 2 },
  modalPreviewTitle: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: palette.foreground },
  modalPreviewSubtitle: { fontSize: 12, lineHeight: 16, color: palette.mutedForeground },
  modalActions: { gap: 10 },
  modalSecondaryButton: {
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
  },
  modalSecondaryButtonText: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: palette.foreground },
  modalPrimaryButton: {
    minHeight: 50,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.secondary,
  },
  modalPrimaryButtonText: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: palette.surface },
  sheetBackdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(18, 24, 35, 0.34)" },
  infoSheet: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#FFF8F4",
    paddingHorizontal: 20,
    paddingTop: 10,
    gap: 14,
  },
  infoSheetHandle: {
    alignSelf: "center",
    width: 56,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#FFD6E4",
  },
  infoSheetHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  infoSheetTitle: { fontSize: 24, lineHeight: 30, fontWeight: "800", color: palette.foreground },
  infoSheetClose: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFE8F0",
  },
  infoSheetCard: {
    padding: 16,
    borderRadius: 26,
    backgroundColor: palette.surface,
    gap: 12,
  },
  infoSheetSectionTitle: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: palette.foreground },
  infoSheetRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  infoSheetRowIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFEAF3",
  },
  infoSheetRowCopy: { flex: 1, gap: 2 },
  infoSheetRowLabel: {
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "700",
    color: palette.primary,
    textTransform: "uppercase",
  },
  infoSheetRowValue: { fontSize: 14, lineHeight: 20, color: palette.foreground },
  infoSheetMetricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  infoMiniCard: {
    minWidth: "47%",
    flex: 1,
    minHeight: 92,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: palette.surfaceMuted,
    gap: 8,
  },
  infoMiniCardIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFEAF3",
  },
  infoMiniCardLabel: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    color: palette.mutedForeground,
    textTransform: "uppercase",
  },
  infoMiniCardValue: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  infoSheetChipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  infoSheetChip: {
    minHeight: 34,
    paddingHorizontal: 10,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
  },
  infoSheetChipText: { fontSize: 12, lineHeight: 16, color: palette.foreground },
  infoSheetReviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  infoSheetReviewLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  infoSheetReviewLinkText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.secondary,
  },
  offerSheetHero: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 16,
    borderRadius: 24,
    backgroundColor: "#FFF0F6",
    borderWidth: 1,
    borderColor: "#FFD6E4",
  },
  offerSheetIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
  },
  offerSheetCopy: {
    flex: 1,
    gap: 5,
  },
  offerSheetTitle: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "900",
    color: palette.foreground,
  },
  offerSheetSubtitle: {
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  customSheet: {
    maxHeight: "86%",
    paddingTop: 10,
    paddingHorizontal: 20,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: palette.background,
    gap: 14,
  },
  customBottomSheetContent: {
    flex: 1,
    paddingBottom: 0,
  },
  customScrollArea: {
    flex: 1,
  },
  customHandle: {
    alignSelf: "center",
    width: 56,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#F0D6C7",
  },
  customHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  customHeaderCopy: { flex: 1, gap: 2 },
  customKicker: {
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "700",
    color: palette.secondary,
    textTransform: "uppercase",
  },
  customTitle: { fontSize: 20, lineHeight: 25, fontWeight: "800", color: palette.foreground },
  customCloseButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
  },
  customHeroCard: {
    flexDirection: "row",
    gap: 12,
    padding: 14,
    borderRadius: 24,
    backgroundColor: palette.surface,
  },
  customHeroImage: { width: 86, height: 86, borderRadius: 18, backgroundColor: palette.surfaceMuted },
  customHeroImageFallback: { width: 86, height: 86, borderRadius: 18, backgroundColor: palette.surfaceMuted },
  customHeroCopy: { flex: 1, gap: 4 },
  customHeroTitle: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: palette.foreground },
  customHeroDescription: { fontSize: 12, lineHeight: 16, color: palette.mutedForeground },
  customHeroPrice: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: palette.primary },
  customContent: { gap: 12, paddingBottom: 4 },
  simpleItemCard: {
    padding: 16,
    borderRadius: 22,
    backgroundColor: palette.surface,
    gap: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  simpleItemBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "#FFF0F6",
  },
  simpleItemBadgeText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    color: palette.secondary,
  },
  simpleItemBody: {
    fontSize: 14,
    lineHeight: 20,
    color: palette.mutedForeground,
  },
  groupCard: {
    padding: 14,
    borderRadius: 22,
    backgroundColor: palette.surface,
    gap: 10,
  },
  groupCardWarning: { borderWidth: 1, borderColor: "#FFD4C4" },
  groupHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  groupTitleWrap: { flex: 1, gap: 2 },
  groupTitle: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: palette.foreground },
  groupMeta: { fontSize: 12, lineHeight: 16, color: palette.mutedForeground },
  optionsList: { gap: 10 },
  optionCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 10,
    borderRadius: 18,
    backgroundColor: palette.background,
  },
  optionCardSelected: { backgroundColor: "#FFF0E8" },
  optionIndicator: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
  },
  optionIndicatorSelected: { backgroundColor: palette.secondary },
  optionCopy: { flex: 1, gap: 2 },
  optionTitle: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: palette.foreground },
  optionSubtitle: { fontSize: 12, lineHeight: 16, color: palette.mutedForeground },
  customFooter: { flexDirection: "row", alignItems: "center", gap: 14, paddingBottom: 18 },
  quantityWrap: {
    width: 116,
    height: 48,
    paddingHorizontal: 6,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: palette.surface,
  },
  quantityButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceMuted,
  },
  quantityButtonPrimary: { backgroundColor: palette.secondary },
  submitButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.secondary,
  },
  submitButtonDisabled: { backgroundColor: palette.foreground },
  submitButtonText: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: palette.surface },
});
