import { StyleSheet } from "react-native";

import { palette } from "@/src/theme/palette";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  content: {
    gap: 16,
    paddingBottom: 36,
  },
  header: {
    paddingHorizontal: 18,
    paddingTop: 8,
    flexDirection: "row",
    gap: 12,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
    shadowColor: palette.shadow,
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  headerCopy: {
    flex: 1,
    gap: 2,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: palette.foreground,
  },
  subtitle: {
    fontSize: 14,
    lineHeight: 21,
    color: palette.mutedForeground,
  },
  networkCard: {
    marginHorizontal: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  networkCardWarning: {
    backgroundColor: "#FFF0F6",
    borderColor: "#FFD7C7",
  },
  networkCardInfo: {
    backgroundColor: "#FFF2F8",
    borderColor: "#FFD6E7",
  },
  networkCopy: {
    flex: 1,
    gap: 3,
  },
  networkTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: palette.foreground,
  },
  networkSubtitle: {
    fontSize: 13,
    lineHeight: 19,
    color: palette.mutedForeground,
  },
  networkActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  networkAction: {
    minHeight: 34,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  networkActionPrimary: {
    backgroundColor: palette.secondary,
    borderColor: palette.secondary,
  },
  networkActionText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: palette.foreground,
  },
  networkActionPrimaryText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: palette.surface,
  },
  offlineWrap: {
    marginHorizontal: 18,
  },
  reorderContextCard: {
    marginHorizontal: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 22,
    backgroundColor: "#FFEAF3",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  reorderContextIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFFCC",
  },
  reorderContextCopy: {
    flex: 1,
    gap: 3,
  },
  reorderContextTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: palette.foreground,
  },
  reorderContextSubtitle: {
    fontSize: 12,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  reorderContextDismiss: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFFA8",
  },
  section: {
    gap: 6,
  },
  sectionHeader: {
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: palette.foreground,
  },
  sectionHint: {
    fontSize: 12,
    color: palette.mutedForeground,
  },
  addressCard: {
    marginHorizontal: 18,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#F0E2D8",
  },
  addressIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF0F6",
    marginTop: 1,
  },
  addressCopy: {
    flex: 1,
    gap: 0,
  },
  addressTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  addressTitle: {
    flex: 1,
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
    color: palette.foreground,
  },
  changePill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "#FFF0F6",
    marginTop: 0,
  },
  changePillText: {
    fontSize: 11,
    fontWeight: "800",
    color: palette.secondary,
  },
  addressLine: {
    fontSize: 12,
    lineHeight: 17,
    color: palette.mutedForeground,
  },
  surfaceCard: {
    marginHorizontal: 18,
    padding: 16,
    borderRadius: 26,
    backgroundColor: palette.surface,
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  voucherRow: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  voucherHintText: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
    color: palette.mutedForeground,
  },
  voucherInput: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.background,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 14,
    color: palette.foreground,
  },
  voucherButton: {
    minHeight: 46,
    paddingHorizontal: 16,
    borderRadius: 18,
    backgroundColor: palette.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  voucherButtonDisabled: {
    opacity: 0.62,
  },
  voucherButtonText: {
    fontSize: 13,
    fontWeight: "800",
    color: palette.surface,
  },
  voucherFeedbackText: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  voucherFeedbackTextSuccess: {
    color: palette.successText,
  },
  voucherFeedbackTextError: {
    color: "#C62828",
  },
  voucherAppliedRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  voucherAppliedText: {
    fontSize: 13,
    fontWeight: "700",
    color: palette.foreground,
  },
  voucherRemoveText: {
    fontSize: 12,
    fontWeight: "700",
    color: palette.secondary,
  },
  voucherSavedText: {
    fontSize: 12,
    fontWeight: "800",
    color: palette.successText,
  },
  paymentList: {
    paddingHorizontal: 18,
    gap: 10,
  },
  paymentCard: {
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F0D7E1",
    backgroundColor: palette.surface,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.03,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 0,
  },
  paymentCardActive: {
    borderColor: palette.secondary,
    backgroundColor: "#FFF3F8",
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  paymentIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
  },
  paymentCopy: {
    flex: 1,
    gap: 2,
  },
  paymentTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: palette.foreground,
  },
  paymentSubtitle: {
    fontSize: 12,
    lineHeight: 17,
    color: palette.mutedForeground,
  },
  errorText: {
    marginHorizontal: 18,
    fontSize: 12,
    lineHeight: 18,
    color: "#C62828",
  },
  summaryCard: {
    marginHorizontal: 18,
    padding: 18,
    borderRadius: 28,
    backgroundColor: palette.surface,
    gap: 14,
    shadowColor: palette.shadow,
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  summaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  summaryMeta: {
    fontSize: 12,
    marginTop: 2,
    color: palette.mutedForeground,
  },
  changeButton: {
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: palette.surfaceMuted,
  },
  changeButtonText: {
    fontSize: 12,
    fontWeight: "700",
    color: palette.foreground,
  },
  summaryItemList: {
    gap: 10,
  },
  summaryItemRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  summaryItemCopy: {
    flex: 1,
    gap: 3,
  },
  summaryItemName: {
    fontSize: 14,
    color: palette.foreground,
    fontWeight: "600",
  },
  summaryItemMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  summaryItemMeta: {
    fontSize: 12,
    color: palette.mutedForeground,
  },
  itemUpdatedBadge: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    color: palette.secondary,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  summaryItemPrice: {
    fontSize: 12,
    color: palette.foreground,
    fontWeight: "600",
  },
  summaryTotals: {
    gap: 10,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  summaryRowLabel: {
    fontSize: 14,
    color: palette.mutedForeground,
  },
  summaryRowValue: {
    fontSize: 14,
    color: palette.foreground,
    fontWeight: "600",
  },
  summaryRowHighlight: {
    color: palette.successText,
  },
  summaryRowStrong: {
    fontSize: 15,
    fontWeight: "800",
    color: palette.foreground,
  },
  divider: {
    height: 1,
    backgroundColor: palette.border,
    marginVertical: 2,
  },
  summaryHint: {
    fontSize: 12,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  footerWrap: {
    position: "absolute",
    left: 18,
    right: 18,
    bottom: 0,
  },
  footerCard: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 28,
    backgroundColor: palette.secondary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.18,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  footerCopy: {
    flex: 1,
    gap: 2,
  },
  footerLabel: {
    fontSize: 12,
    color: "rgba(255,255,255,0.82)",
  },
  footerAmount: {
    fontSize: 22,
    fontWeight: "800",
    color: palette.surface,
  },
  placeOrderButtonLift: {
    borderRadius: 999,
    shadowColor: "#111827",
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 5,
  },
  placeOrderButtonLiftDisabled: {
    shadowOpacity: 0,
    elevation: 0,
  },
  placeOrderButton: {
    overflow: "hidden",
    minWidth: 156,
    height: 46,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
    paddingHorizontal: 16,
  },
  placeOrderButtonDisabled: {
    opacity: 0.72,
  },
  placeOrderButtonSheen: {
    position: "absolute",
    left: 16,
    right: 16,
    top: 1,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  placeOrderButtonText: {
    fontSize: 14,
    fontWeight: "800",
    color: palette.secondary,
  },
  footerNote: {
    marginTop: 8,
    paddingHorizontal: 6,
    fontSize: 12,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  footerError: {
    marginTop: 8,
    paddingHorizontal: 6,
    fontSize: 12,
    lineHeight: 18,
    color: "#D83A66",
  },
});
