import { StyleSheet } from "react-native";

import { palette } from "@/src/theme/palette";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  screenBody: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
  },
  headerCopy: {
    flex: 1,
    gap: 3,
  },
  headerButton: {
    width: 44,
    height: 44,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 18,
    elevation: 4,
  },
  headerBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    minHeight: 24,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "#FFEAF1",
  },
  headerBadgeText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    color: palette.secondary,
  },
  headerTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    color: palette.foreground,
  },
  headerSubtitle: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  headerLocateButton: {
    width: 44,
    height: 44,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.sky,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 18,
    elevation: 4,
  },
  mapWrap: {
    flex: 1,
    marginHorizontal: 14,
    borderRadius: 30,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: "#F8EFE8",
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.9,
    shadowRadius: 22,
    elevation: 4,
  },
  map: {
    flex: 1,
  },
  mapFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    gap: 10,
    backgroundColor: palette.background,
  },
  mapFallbackTitle: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "700",
    color: palette.foreground,
    textAlign: "center",
  },
  mapFallbackText: {
    fontSize: 14,
    lineHeight: 22,
    color: palette.mutedForeground,
    textAlign: "center",
  },
  mapFallbackButton: {
    minHeight: 44,
    marginTop: 4,
    borderRadius: 999,
    paddingHorizontal: 16,
    backgroundColor: palette.foreground,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  mapFallbackButtonText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  centerPinWrap: {
    position: "absolute",
    top: "50%",
    left: 0,
    right: 0,
    alignItems: "center",
    marginTop: -34,
  },
  mapHintPill: {
    position: "absolute",
    top: 16,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.8,
    shadowRadius: 16,
    elevation: 4,
  },
  mapHintPillText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: palette.foreground,
  },
  pinHalo: {
    position: "absolute",
    width: 46,
    height: 46,
    borderRadius: 999,
    backgroundColor: "rgba(255, 99, 146, 0.26)",
  },
  pinShadow: {
    position: "absolute",
    bottom: -8,
    width: 26,
    height: 10,
    borderRadius: 999,
    backgroundColor: "#000000",
  },
  pinWrap: {
    alignItems: "center",
    justifyContent: "center",
    shadowColor: palette.secondary,
    shadowOpacity: 0.24,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  currentLocationFab: {
    position: "absolute",
    right: 14,
  },
  currentLocationFabInner: {
    width: 54,
    height: 54,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 7,
  },
  bottomCard: {
    overflow: "hidden",
    marginHorizontal: 14,
    marginTop: 10,
    paddingHorizontal: 18,
    paddingTop: 18,
    borderRadius: 30,
    backgroundColor: palette.surface,
    gap: 12,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.9,
    shadowRadius: 22,
    elevation: 7,
  },
  bottomTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    minHeight: 84,
  },
  bottomIcon: {
    width: 42,
    height: 42,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EBF1FF",
  },
  bottomCopy: {
    flex: 1,
    gap: 4,
    minHeight: 84,
  },
  bottomLabel: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
    color: palette.mutedForeground,
    textTransform: "uppercase",
    letterSpacing: 0,
  },
  bottomTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "800",
    color: palette.foreground,
  },
  bottomSubtitle: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  statusPill: {
    width: 30,
    height: 30,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF2C8",
  },
  manualFieldWrap: {
    gap: 7,
  },
  manualFieldLabel: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
    color: palette.mutedForeground,
    textTransform: "uppercase",
    letterSpacing: 0,
  },
  manualFieldShell: {
    minHeight: 52,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#EFCFD9",
    backgroundColor: "#FFF9FB",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 1,
  },
  manualFieldShellMultiline: {
    minHeight: 72,
    alignItems: "flex-start",
    paddingTop: 12,
  },
  manualFieldIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFEAF1",
  },
  manualFieldInput: {
    flex: 1,
    minHeight: 48,
    paddingVertical: 12,
    fontSize: 15,
    lineHeight: 23,
    fontWeight: "600",
    color: palette.foreground,
  },
  manualFieldInputMultiline: {
    minHeight: 58,
    paddingTop: 0,
  },
  confirmButtonLift: {
    borderRadius: 28,
    marginTop: 3,
    shadowColor: "#111827",
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 9 },
    elevation: 6,
  },
  confirmButton: {
    overflow: "hidden",
    minHeight: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.secondary,
    paddingHorizontal: 18,
    paddingVertical: 15,
  },
  confirmButtonGlow: {
    position: "absolute",
    top: -28,
    right: -20,
    width: 118,
    height: 118,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  confirmButtonSheen: {
    position: "absolute",
    left: 20,
    right: 20,
    top: 1,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.38)",
  },
  confirmButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  confirmButtonDisabled: {
    opacity: 0.7,
  },
  confirmButtonText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.surface,
  },
});
